# Generated by Django 5.0.3 on 2024-03-29 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='data_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 18, 41, 23, 361912, tzinfo=datetime.timezone.utc)),
        ),
    ]
